import fs from "fs";
import path from "path";

type ContractRecord = Record<
  string,
  { address: string; abi: unknown; constructorArguments: unknown[] }
>;
type Deployments = Record<string, ContractRecord>;

const DEPLOYMENTS_JSON = path.join(__dirname, "..", "..", "deployments.json");
const SHARED_CONTRACTS_TS = path.join(
  __dirname,
  "..",
  "..",
  "..",
  "shared",
  "src",
  "contracts.ts"
);
const SHARED_CONTRACTS_JS = path.join(
  __dirname,
  "..",
  "..",
  "..",
  "shared",
  "src",
  "contracts.js"
);

function readDeployments(): Deployments {
  if (!fs.existsSync(DEPLOYMENTS_JSON)) return {};
  return JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf8"));
}

function persistDeployments(all: Deployments): void {
  fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(all, null, 2) + "\n");

  fs.mkdirSync(path.dirname(SHARED_CONTRACTS_TS), { recursive: true });
  fs.writeFileSync(
    SHARED_CONTRACTS_TS,
    `// Auto-generated by \`npm run deploy:testnet\`.
// Do not edit by hand — changes are overwritten on the next deploy.

export const deployments = ${JSON.stringify(all, null, 2)} as const;

export type NetworkName = keyof typeof deployments;
`
  );
  fs.writeFileSync(
    SHARED_CONTRACTS_JS,
    `"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deployments = void 0;
exports.deployments = ${JSON.stringify(all, null, 2)};
`
  );
}

export function markRoboPayLegacy(): void {
  const all = readDeployments();
  const testnet = all.testnet;
  if (!testnet?.RoboPay) {
    if (testnet?.RoboPayLegacy) {
      persistDeployments(all);
      return;
    }
    throw new Error("No existing RoboPay testnet deployment was found to mark as legacy.");
  }

  testnet.RoboPayLegacy = testnet.RoboPayLegacy || testnet.RoboPay;
  delete testnet.RoboPay;
  persistDeployments(all);
}

export function writeDeploymentAddresses(network: string, deployed: ContractRecord): void {
  const all = readDeployments();
  if (network === "testnet" && deployed.RoboPayEscrow && all.testnet?.RoboPay) {
    const existing = all.testnet.RoboPay;
    if (existing.address.toLowerCase() !== deployed.RoboPayEscrow.address.toLowerCase()) {
      all.testnet.RoboPayLegacy = all.testnet.RoboPayLegacy || existing;
      delete all.testnet.RoboPay;
    }
  }
  all[network] = { ...(all[network] || {}), ...deployed };
  persistDeployments(all);
}
